import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
// import { Button } from '@material-tailwind/react'
import Navbar from '../components/Navbar'
import NewsSec from '@/components/NewsSec'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <>
        {/* <Navbar /> */}
        <div className="m-auto">
          <NewsSec />
        </div>
      </>
    </>
  )
}
